In [1]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from colorama import Fore, Style
import json
import glob
import re
import numpy as np
import pandas as pd
import time


def ouvrir_json(chemin):
    f = open(chemin, encoding="utf-8")
    toto = json.load(f)
    f.close()
    return toto

In [2]:
def similarité(model):
    fichier = glob.glob("appariements_faq/*.json")
        #print(fichier)
    for j in fichier:
        f=re.findall(r'\b\d[a-zA-Z_0-9]*', j)
        print("-"*60)
        print("| fichier : {}, model utilisé : {}|".format(f,model))
        print("-"*60)
        data= ouvrir_json(j)
        questions = []
        reponses = []
        for cle, valeur in data.items():
            questions.append(valeur[0])
            reponses.append(valeur[1])
        index = 0
        for question in questions:
            index += 1
            qr_vecs = SentenceTransformer(model).encode([question]+reponses)
            cos_sim = cosine_similarity ([qr_vecs[0]],qr_vecs[1:])
            n=0
            while n <len(max(cos_sim)):
                if max(cos_sim)[n]==np.max(cos_sim):
                    position=n+1

                    if index == position:
                        b=(f'{Fore.GREEN}bonne{Style.RESET_ALL}')
                        print('La réponse {} est la plus proche de la question {}, avec un score de {} : la réponse est {}'.format(position,index,round(np.max(cos_sim),8),b))
                    else:
                        m=(f'{Fore.RED}mauvaise{Style.RESET_ALL}')
                        print('La réponse {} est la plus proche de la question {}, avec un score de {} : la réponse est {}'.format(position,index,round(np.max(cos_sim),8),m))
                    break
                else:
                     n=n+1

In [4]:
start = time.time()
similarité('all-mpnet-base-v2')
end = time.time()
print("-"*60)
print(f"le temps d'exécution: {end - start} secondes")

------------------------------------------------------------
| fichier : ['3_faq_syp'], model utilisé : all-mpnet-base-v2|
------------------------------------------------------------
La réponse 1 est la plus proche de la question 1, avec un score de 0.38027599453926086 : la réponse est bonne
La réponse 9 est la plus proche de la question 2, avec un score de 0.46388840675354004 : la réponse est mauvaise
La réponse 7 est la plus proche de la question 3, avec un score de 0.48737582564353943 : la réponse est mauvaise
La réponse 4 est la plus proche de la question 4, avec un score de 0.5575613975524902 : la réponse est bonne
La réponse 7 est la plus proche de la question 5, avec un score de 0.4608323872089386 : la réponse est mauvaise
La réponse 5 est la plus proche de la question 6, avec un score de 0.3509013056755066 : la réponse est mauvaise
La réponse 9 est la plus proche de la question 7, avec un score de 0.4993944764137268 : la réponse est mauvaise
La réponse 9 est la plus proche de 

La réponse 2 est la plus proche de la question 2, avec un score de 0.5842032432556152 : la réponse est bonne
La réponse 1 est la plus proche de la question 3, avec un score de 0.6729766130447388 : la réponse est mauvaise
La réponse 14 est la plus proche de la question 4, avec un score de 0.7114912867546082 : la réponse est mauvaise
La réponse 1 est la plus proche de la question 5, avec un score de 0.7325258255004883 : la réponse est mauvaise
La réponse 3 est la plus proche de la question 6, avec un score de 0.6051297187805176 : la réponse est mauvaise
La réponse 11 est la plus proche de la question 7, avec un score de 0.7401167750358582 : la réponse est mauvaise
La réponse 8 est la plus proche de la question 8, avec un score de 0.6988641023635864 : la réponse est bonne
La réponse 9 est la plus proche de la question 9, avec un score de 0.6194704174995422 : la réponse est bonne
La réponse 10 est la plus proche de la question 10, avec un score de 0.7941977381706238 : la réponse est bonne


In [5]:
start = time.time()
similarité('all-MiniLM-L6-v2')
end = time.time()
print("-"*60)
print(f"le temps d'exécution: {end - start} secondes")

------------------------------------------------------------
| fichier : ['3_faq_syp'], model utilisé : all-MiniLM-L6-v2|
------------------------------------------------------------
La réponse 10 est la plus proche de la question 1, avec un score de 0.42461133003234863 : la réponse est mauvaise
La réponse 7 est la plus proche de la question 2, avec un score de 0.4828810691833496 : la réponse est mauvaise
La réponse 9 est la plus proche de la question 3, avec un score de 0.5143042802810669 : la réponse est mauvaise
La réponse 4 est la plus proche de la question 4, avec un score de 0.6079043745994568 : la réponse est bonne
La réponse 8 est la plus proche de la question 5, avec un score de 0.5011932849884033 : la réponse est mauvaise
La réponse 5 est la plus proche de la question 6, avec un score de 0.3384901285171509 : la réponse est mauvaise
La réponse 10 est la plus proche de la question 7, avec un score de 0.44876012206077576 : la réponse est mauvaise
La réponse 9 est la plus proche 

La réponse 2 est la plus proche de la question 2, avec un score de 0.5938749313354492 : la réponse est bonne
La réponse 1 est la plus proche de la question 3, avec un score de 0.6910389065742493 : la réponse est mauvaise
La réponse 14 est la plus proche de la question 4, avec un score de 0.830909252166748 : la réponse est mauvaise
La réponse 25 est la plus proche de la question 5, avec un score de 0.7186660766601562 : la réponse est mauvaise
La réponse 3 est la plus proche de la question 6, avec un score de 0.5796977877616882 : la réponse est mauvaise
La réponse 10 est la plus proche de la question 7, avec un score de 0.688241183757782 : la réponse est mauvaise
La réponse 8 est la plus proche de la question 8, avec un score de 0.7829321026802063 : la réponse est bonne
La réponse 9 est la plus proche de la question 9, avec un score de 0.6242268681526184 : la réponse est bonne
La réponse 10 est la plus proche de la question 10, avec un score de 0.8242620229721069 : la réponse est bonne
L

In [6]:
start = time.time()
similarité('distiluse-base-multilingual-cased-v1')
end = time.time()
print("-"*60)
print(f"le temps d'exécution: {end - start} secondes")

------------------------------------------------------------
| fichier : ['3_faq_syp'], model utilisé : distiluse-base-multilingual-cased-v1|
------------------------------------------------------------
La réponse 1 est la plus proche de la question 1, avec un score de 0.1497001349925995 : la réponse est bonne
La réponse 6 est la plus proche de la question 2, avec un score de 0.02052959054708481 : la réponse est mauvaise
La réponse 3 est la plus proche de la question 3, avec un score de 0.26683586835861206 : la réponse est bonne
La réponse 4 est la plus proche de la question 4, avec un score de 0.3101908564567566 : la réponse est bonne
La réponse 8 est la plus proche de la question 5, avec un score de 0.05784862861037254 : la réponse est mauvaise
La réponse 8 est la plus proche de la question 6, avec un score de 0.22108405828475952 : la réponse est mauvaise
La réponse 10 est la plus proche de la question 7, avec un score de 0.09060856699943542 : la réponse est mauvaise
La réponse 8 est

La réponse 2 est la plus proche de la question 1, avec un score de 0.379741907119751 : la réponse est mauvaise
La réponse 2 est la plus proche de la question 2, avec un score de 0.533539891242981 : la réponse est bonne
La réponse 3 est la plus proche de la question 3, avec un score de 0.6472136974334717 : la réponse est bonne
La réponse 6 est la plus proche de la question 4, avec un score de 0.47084006667137146 : la réponse est mauvaise
La réponse 2 est la plus proche de la question 5, avec un score de 0.34440580010414124 : la réponse est mauvaise
La réponse 3 est la plus proche de la question 6, avec un score de 0.3232901990413666 : la réponse est mauvaise
La réponse 27 est la plus proche de la question 7, avec un score de 0.5900623202323914 : la réponse est mauvaise
La réponse 8 est la plus proche de la question 8, avec un score de 0.4896220862865448 : la réponse est bonne
La réponse 2 est la plus proche de la question 9, avec un score de 0.3814210295677185 : la réponse est mauvaise


In [39]:
fichier = glob.glob("appariements_faq/1_faq_dmc.json")
        #print(fichier)
for j in fichier:
    f=re.findall(r'\b\d[a-zA-Z_0-9]*', j)
    data= ouvrir_json(j)
    questions = []
    reponses = []
    for cle, valeur in data.items():
        questions.append(valeur[0])
        reponses.append(valeur[1])
    for question in questions:
        qr_vecs = SentenceTransformer('all-mpnet-base-v2').encode([question]+reponses)
        cos_sim = cosine_similarity ([qr_vecs[0]],qr_vecs[1:])
        print(cos_sim)

[[0.71185875 0.37251708 0.3110036  0.34850842 0.4142125 ]]
[[0.4304372  0.5716425  0.23419383 0.25605336 0.4078042 ]]
[[0.46373165 0.34188882 0.41454935 0.18261684 0.27809787]]
[[0.45965308 0.2734798  0.22889712 0.32000312 0.32531157]]
[[0.28866747 0.27755308 0.37332416 0.36554644 0.48555362]]
